"use client"; // Use the 'use client' directive at the top
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { Suspense } from "react";
import Loading from "./loading";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const inter = Roboto({ subsets: ["latin"], weight: "500" });
const queryClient = new QueryClient();

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <QueryClientProvider client={queryClient}>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          <Suspense fallback={<Loading />}>{children}</Suspense>
          <Footer />
        </body>
      </html>
    </QueryClientProvider>
  );
}
